apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
  labels:
    app: web-nginx
    tier: web
spec:
  type: ClusterIP
  selector:
    app: web-nginx
    tier: web
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
